import io
import zipfile
from chat.models import GeneratedCode

class ZipArchiver:
    @classmethod
    def create_project_zip(cls, session) -> bytes:
        buffer = io.BytesIO()
        codes = GeneratedCode.objects.filter(session=session)
        
        with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
            for code_obj in codes:
                filename = code_obj.module_name
                zf.writestr(filename, code_obj.code_content)
                
            # Add a README.md to the downloaded zip archive
            readme_content = (
                f"# Generated Project - {session.title}\n\n"
                f"Generated by DevDialogue AI on {session.started_at.strftime('%Y-%m-%d %H:%M:%S')}.\n\n"
                "## Files Included:\n" +
                "\n".join([f"- `{c.module_name}`" for c in codes])
            )
            zf.writestr("README.md", readme_content)
            
        buffer.seek(0)
        return buffer.getvalue()
